# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Payyus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Fabric'
  pod 'Crashlytics', '~> 3.9.3'
  pod 'LGSideMenuController', '~> 2.1.1'
  pod 'Alamofire', '~> 4.7.0'
  pod 'EVReflection', '~> 5.5.1'
  pod 'SwiftyJSON'
  pod 'IQKeyboardManager', '~> 5.0.0'
  pod 'Plaid', '~> 1.1.0'
  pod 'RNCryptor', '~> 5.0'
  pod 'SocketRocket', '~>0.5.0'
  pod 'SDWebImage', '~> 4.0'
  # Pods for Payyus
end
